#pragma once

// DEBUG
#define DEBUG_LEVEL DBG_NONE
#define DEBUG_PORT 115200

// HOMEKIT
#define HOMEKIT_PASSWORD "222-22-222"

// CONTROLLER
#define ACTUATOR1_PIN D1
#define ACTUATOR2_PIN D2
#define ACTUATOR3_PIN D5
#define ACTUATOR4_PIN D7
